CREATE OR REPLACE PACKAGE GESTIONARE_BILETE IS

    TYPE TIPBILET IS RECORD (
        ID_BILET BILETE.ID_BILET%TYPE,
        PRET BILETE.PRET%TYPE,
        ID_PROIECTIE BILETE.ID_PROIECTIE%TYPE,
        ID_SCAUN BILETE.ID_SCAUN%TYPE,
        ID_CLIENT BILETE.ID_CLIENT%TYPE
    );

    TYPE TIPCLIENT IS RECORD (
        ID_CLIENT CLIENTI.ID_CLIENT%TYPE,
        NUME CLIENTI.NUME%TYPE,
        PRENUME CLIENTI.PRENUME%TYPE,
        DATA_NASTERII CLIENTI.DATA_NASTERII%TYPE,
        TELEFON CLIENTI.TELEFON%TYPE
    );

    TYPE TabelBilete IS TABLE OF TIPBILET INDEX BY PLS_INTEGER;
    T_bilete TabelBilete;

    TYPE TabelClienti IS TABLE OF TIPCLIENT INDEX BY PLS_INTEGER;
    T_clienti TabelClienti;

    FUNCTION OBTINEREINFOBILET(P_ID_BILET BILETE.ID_BILET%TYPE) RETURN TIPBILET;
    FUNCTION OBTINEREINFOCLIENT(P_ID_CLIENT CLIENTI.ID_CLIENT%TYPE) RETURN TIPCLIENT;
    PROCEDURE ADAUGACLIENT(
        P_NUME CLIENTI.NUME%TYPE,
        P_PRENUME CLIENTI.PRENUME%TYPE,
        P_DATA_NASTERII CLIENTI.DATA_NASTERII%TYPE,
        P_TELEFON CLIENTI.TELEFON%TYPE
    );
    PROCEDURE ADAUGABILET(
        P_PRET BILETE.PRET%TYPE,
        P_ID_PROIECTIE BILETE.ID_PROIECTIE%TYPE,
        P_ID_SCAUN BILETE.ID_SCAUN%TYPE,
        P_ID_CLIENT BILETE.ID_CLIENT%TYPE
    );
END GESTIONARE_BILETE;
/

CREATE OR REPLACE PACKAGE BODY GESTIONARE_BILETE AS
    FUNCTION OBTINEREINFOBILET(P_ID_BILET BILETE.ID_BILET%TYPE) RETURN TIPBILET IS 
    BEGIN 
        RETURN T_BILETE(P_ID_BILET);
    END OBTINEREINFOBILET;

    FUNCTION OBTINEREINFOCLIENT(P_ID_CLIENT CLIENTI.ID_CLIENT%TYPE) RETURN TIPCLIENT IS 
    BEGIN 
        RETURN T_CLIENTI(P_ID_CLIENT);
    END OBTINEREINFOCLIENT;

    PROCEDURE ADAUGACLIENT(
        P_NUME CLIENTI.NUME%TYPE,
        P_PRENUME CLIENTI.PRENUME%TYPE,
        P_DATA_NASTERII CLIENTI.DATA_NASTERII%TYPE,
        P_TELEFON CLIENTI.TELEFON%TYPE
    ) IS 
    BEGIN
        T_clienti(T_clienti.COUNT + 1).id_client := T_clienti.COUNT + 1;
        T_clienti(T_clienti.COUNT).nume := P_NUME;
        T_clienti(T_clienti.COUNT).prenume := P_PRENUME;
        T_clienti(T_clienti.COUNT).data_nasterii := P_DATA_NASTERII;
        T_clienti(T_clienti.COUNT).telefon := P_TELEFON;
    END ADAUGACLIENT;

    PROCEDURE ADAUGABILET(
        P_PRET BILETE.PRET%TYPE,
        P_ID_PROIECTIE BILETE.ID_PROIECTIE%TYPE,
        P_ID_SCAUN BILETE.ID_SCAUN%TYPE,
        P_ID_CLIENT BILETE.ID_CLIENT%TYPE
    ) IS
    BEGIN
        T_bilete(T_bilete.COUNT + 1).id_bilet := T_bilete.COUNT + 1;
        T_bilete(T_bilete.COUNT).pret := P_PRET;
        T_bilete(T_bilete.COUNT).id_proiectie := P_ID_PROIECTIE;
        T_bilete(T_bilete.COUNT).id_scaun := P_ID_SCAUN;
        T_bilete(T_bilete.COUNT).id_client := P_ID_CLIENT;
    END ADAUGABILET;
END GESTIONARE_BILETE;
/

DECLARE
    v_info_bilet GESTIONARE_BILETE.TIPBILET;
    v_info_client GESTIONARE_BILETE.TIPCLIENT;
BEGIN
    -- Adaugare client
    GESTIONARE_BILETE.ADAUGACLIENT('Balaita', 'Cosmin', TO_DATE('2003-12-04', 'YYYY-MM-DD'), '123456789');

    -- Afisare informatii despre clientul adaugat
    v_info_client := GESTIONARE_BILETE.OBTINEREINFOCLIENT(1);
    DBMS_OUTPUT.PUT_LINE('Informatii client:');
    DBMS_OUTPUT.PUT_LINE('ID_CLIENT: ' || v_info_client.ID_CLIENT);
    DBMS_OUTPUT.PUT_LINE('NUME: ' || v_info_client.NUME);
    DBMS_OUTPUT.PUT_LINE('PRENUME: ' || v_info_client.PRENUME);
    DBMS_OUTPUT.PUT_LINE('DATA_NASTERII: ' || TO_CHAR(v_info_client.DATA_NASTERII, 'YYYY-MM-DD'));
    DBMS_OUTPUT.PUT_LINE('TELEFON: ' || v_info_client.TELEFON);
    
    -- Adaugare bilet
    GESTIONARE_BILETE.ADAUGABILET(50.0, 1, 101, 1);

    -- Afisare informatii despre biletul adaugat
    v_info_bilet := GESTIONARE_BILETE.OBTINEREINFOBILET(1);
    DBMS_OUTPUT.PUT_LINE('Informatii bilet:');
    DBMS_OUTPUT.PUT_LINE('ID_BILET: ' || v_info_bilet.ID_BILET);
    DBMS_OUTPUT.PUT_LINE('PRET: ' || v_info_bilet.PRET);
    DBMS_OUTPUT.PUT_LINE('ID_PROIECTIE: ' || v_info_bilet.ID_PROIECTIE);
    DBMS_OUTPUT.PUT_LINE('ID_SCAUN: ' || v_info_bilet.ID_SCAUN);
    DBMS_OUTPUT.PUT_LINE('ID_CLIENT: ' || v_info_bilet.ID_CLIENT);
END;
/

