-- CREARE TABELA REGIZORI
CREATE TABLE REGIZORI(
    ID_REGIZOR INT PRIMARY KEY,
    PRENUME VARCHAR2(20) NOT NULL,
    NUME VARCHAR2(20) NOT NULL
    );
-- CREARE TABELA RATINGS
CREATE TABLE RATINGS(
    ID_RATING INT PRIMARY KEY,
    VALOARE VARCHAR2(6) NOT NULL
    );
-- CREARE TABELA GENURI
CREATE TABLE GENURI(
    ID_GEN INT PRIMARY KEY,
    DENUMIRE VARCHAR2(20) NOT NULL
    );
-- CREARE TABELA FILME
CREATE TABLE FILME(
    ID_FILM INT PRIMARY KEY,
    TITLU VARCHAR2(50) NOT NULL,
    DURATA INT NOT NULL,
    ID_RATING INT,
    ID_REGIZOR INT,
    CONSTRAINT FK_FILME_RATINGS FOREIGN KEY (ID_RATING) REFERENCES RATINGS (ID_RATING),
    CONSTRAINT FK_FILME_REGIZORI FOREIGN KEY (ID_REGIZOR) REFERENCES REGIZORI (ID_REGIZOR)    
);
-- CREARE TABELA ASOCIATIVA FILME_GENURI
CREATE TABLE FILME_GENURI(
    ID_FILM INT,
    ID_GEN INT,
    CONSTRAINT PK_FILME_GENURI PRIMARY KEY(ID_FILM, ID_GEN),
    CONSTRAINT FK_FILME_GENURI_FILME FOREIGN KEY (ID_FILM) REFERENCES FILME (ID_FILM),
    CONSTRAINT FK_FILME_GENURI_GENURI FOREIGN KEY (ID_GEN) REFERENCES GENURI (ID_GEN)
);
-- CREARE TABELA ACTORI
CREATE TABLE ACTORI (
    ID_ACTOR INT PRIMARY KEY,
    NUME VARCHAR2(20) NOT NULL,
    PRENUME VARCHAR2(20) NOT NULL,
    DATA_NASTERII DATE
    );
--CREARE TABELA ASOCIATIVA FILME_ACTORI
CREATE TABLE ACTORI_FILME
(
    ID_ACTOR INT,
    ID_FILM INT,
    CONSTRAINT PK_ACTORI_FILME PRIMARY KEY (ID_ACTOR, ID_FILM),
    CONSTRAINT FK_ACTORI_FILME_ACTORI FOREIGN KEY (ID_ACTOR) REFERENCES ACTORI (ID_ACTOR),
    CONSTRAINT FK_ACTORI_FILME_FILME FOREIGN KEY (ID_FILM) REFERENCES FILME (ID_FILM)
);
--CREARE TABELA CINEMATOGRAFE
CREATE TABLE CINEMATOGRAFE
(
    ID_CINEMATOGRAF INT PRIMARY KEY,
    NUME VARCHAR2(50),
    ORAS VARCHAR2(50) NOT NULL,
    NUMAR_SALI INT 
);
--CREARE TABELA ANGAJATI
CREATE TABLE ANGAJATI
(
    ID_ANGAJAT         INT PRIMARY KEY,
    NUME               VARCHAR2 (100),
    PRENUME            VARCHAR2 (100),
    DATA_NASTERII      DATE,
    FUNCTIE            VARCHAR2 (50),
    SALARIU            INT,
    ID_CINEMATOGRAF    INT,
    CONSTRAINT FK_ANGAJAT_CINAMA FOREIGN KEY (ID_CINEMATOGRAF) REFERENCES CINEMATOGRAFE (ID_CINEMATOGRAF)
);
--CREARE TABELA SALI
CREATE TABLE SALI
(
    ID_SALA INT PRIMARY KEY,
    NUMAR_LOCURI INT,
    ID_CINEMATOGRAF INT,
    CONSTRAINT FK_SALA_CINEMA FOREIGN KEY (ID_CINEMATOGRAF) REFERENCES CINEMATOGRAFE (ID_CINEMATOGRAF)
);
--CREARE TABELA PRIECTII
CREATE TABLE PROIECTII
(
    ID_PROIECTIE INT PRIMARY KEY,
    ID_SALA INT,
    ID_FILM INT,
    DATA_PROIECTIE DATE,
    ORA_INCPERE TIMESTAMP,
    CONSTRAINT FK_PROIECTIE_SALA FOREIGN KEY (ID_SALA) REFERENCES SALI (ID_SALA),
    CONSTRAINT FK_PREIECTIE_FILM FOREIGN KEY (ID_FILM) REFERENCES FILME (ID_FILM)
);
-- CREARE TABELA SCACUNE
CREATE TABLE SCAUNE
(
    ID_SCAUN INT PRIMARY KEY,
    ID_SALA INT,
    NUMAR INT,
    RAND INT,
    CONSTRAINT FK_SCAUN_SALA FOREIGN KEY (ID_SALA) REFERENCES SALI (ID_SALA)
    );
--CREARE TABELA CLIENTI
CREATE TABLE CLIENTI
(
    ID_CLIENT INT PRIMARY KEY,
    NUME VARCHAR2(50),
    PRENUME VARCHAR2(50),
    DATA_NASTERII DATE,
    TELEFON VARCHAR2(15) UNIQUE
);

--CREARE TABELA BILETE
CREATE TABLE BILETE(
    ID_BILET INT PRIMARY KEY,
    PRET INT,
    ID_PROIECTIE INT,
    ID_SCAUN INT,
    ID_CLIENT INT,
    CONSTRAINT FK_BILET_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI (ID_CLIENT),
    CONSTRAINT FK_BILET_SCAUN FOREIGN KEY (ID_SCAUN) REFERENCES SCAUNE (ID_SCAUN),
    CONSTRAINT FK_BILET_PROIECTIE FOREIGN SKEY (ID_PROIECTIE) REFERENCES PROIECTII (ID_PROIECTIE)
 
);
    

    
    